import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the Redux slice
const initialState = {
    // Set the "placename" property based on whether there's a value in localStorage
    placename: localStorage.getItem('placename') ? localStorage.getItem("placename") : "London"
};

// Create a Redux slice named "search"
export const searchSlice = createSlice({
    name: "search", // Name of the slice
    initialState, // Initial state defined above
    reducers: {
        // Define a Redux action creator named "goSearch"
        goSearch: (state, action) => {
            // Extract the new name from the action's payload
            const name = action.payload;
            // Update the "placename" property in the state with the new name
            state.placename = name;
        }
    }
});

// Export the "goSearch" action creator for external use
export const { goSearch } = searchSlice.actions;

// Export the reducer function generated by createSlice
export default searchSlice.reducer;
